name: Push the Docker image to AWS ECR Repo

on:
  push:
    branches:
      - main

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for actions/checkout      

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Options: temurin, zulu, adopt, etc.
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::173254080023:role/githuboidc
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r5j7w2f7

      - name: Build, tag, and push the image to Amazon ECR
        env:
          ECR_PUBLIC_REGISTRY: public.ecr.aws/r5j7w2f7
          ECR_REPOSITORY: demo-docker
          IMAGE_TAG: ${{ env.commit-hash }}-${{ env.timestamp }}
        run: |
          docker build -t $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
